config/routes.rb
Rails.application.routes.draw do
  get 'representatives/index'

  # get 'greeter/hello'

  # SAME AS ABOVE 
  get "greeter/hello" => "greeter#hello"
  get "greeter/goodbye"

  root 'representatives#index'
  # You can have the root of your site routed with "root"
  # root 'welcome#index'
end

app/models/representative.rb
class Representative
  include HTTParty

  base_uri 'http://whoismyrepresentative.com'
  default_params output: "json"
  format :json

  def self.for state
    get("/getall_reps_bystate.php", query: {state: state})["results"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
    random_names = %w{Joe Alex Harry} 
    @name = random_names.sample
    @time = Time.now
    @times_displayed ||= 0
    @times_displayed += 1
  end
end

app/controllers/representatives_controller.rb
class RepresentativesController < ApplicationController
  def index
    @state = params[:state] || 'md' 
    @reps = Representative.for @state.upcase!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
  def formatted_time(time)
    # time string in AM/PM format
    time.strftime("%I:%M%p")
  end
end

app/helpers/representatives_helper.rb
module RepresentativesHelper
end

app/views/greeter/goodbye.html.erb
goodbye

app/views/greeter/hello.html.erb
<h1>Greetings, <%= @name %></h1> 
Time now is <%= formatted_time(@time) %><br/>
This page has been viewed <%= @times_displayed %> time(s)

<p><%= link_to "Goodbye", greeter_goodbye_path %></p>               
<p><%= link_to "Google", "http://www.google.com/" %></p>               

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFirstApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/representatives/index.html.erb
<h1>State - <%= @state %></h1>

<h2>Representatives</h2>

<table>
  <tr>
      <th>Name</th>
      <th>Party</th>
      <th>State</th>
      <th>District</th>
      <th>Phone</th>
      <th>Office</th>
      <th>Contact</th>
  </tr>
  <% @reps.each do |rep| %>      
    <tr class="<%= cycle('even', 'odd') %>">
      <td><%= rep["name"] %></td>
      <td><%= rep["party"] %></td>
      <td><%= rep["state"] %></td>
      <td><%= rep["district"] %></td>
      <td><%= rep["phone"] %></td>
      <td><%= rep["office"] %></td>
      <td><%= link_to "Details", rep["link"], class: "special_link" %></td>
    </tr>
  <% end %>
</table>